name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install LibJQ
        run: |-
          docker run --name "libjq" -d flant/jq:b6be13d5-glibc
          docker cp libjq:/libjq ./libjq 
          docker rm libjq
      - name: Run Tests
        run: |-
          ls -al
          ls -al ./libjq
          CGO_ENABLED=1 CGO_CFLAGS="-I./libjq/include" CGO_LDFLAGS="-L./libjq/lib" go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload Coverage
        run: |-
          bash <(curl -s https://codecov.io/bash)
